### ISSUE TITLE
highlighting stops after a few code lines 

### ISSUE THREAD

**Issue by s-a** [mazurov/sublime-levels#2]
Try http://code.jquery.com/jquery-1.9.1.js.
Highlightling stops at line 344 in my sublime text editor.
I' m using Windows 7

![scope-highlight](https://f.cloud.github.com/assets/1270662/393560/e3080006-a79b-11e2-94d8-e4cb67c66fa8.png)

So i figured out that it works if I RTrim the codelines...

Hope this helps.

**Comment by mazurov** [comment]
Hi @s-a, 

A javascript coloring is based on JsLint validator and I'm sure that the problem is there (as I mentioned in readme - JsLint is not an ideal tool). 

For example, JsLint could not parse those lines:

``` javascript
for ( ; i < length; i++ ) {
}
```

You could check it in the online validator: http://www.jslint.com/

So, the solution is only to wait the next version of sublime-levels which will not be based  on JsLint. I already have some thoughts how to do it.

**Comment by s-a** [comment]
Good morning,
I' m using Uglify.js here https://github.com/s-a/sublime-text-refactor which works fine as Javascript Code parser.
Maybe this is helpfull for you.

Best regards!

**Comment by mazurov** [comment]
JsLint has the `color` function, that returns a scope nesting information. I'm going to extend  the esprima.js parsing tools and get the same information.
